name: 🐛Bug Report
description: Use this template to file a bug report.
title: '[BUG]: '
labels: ['bug :bug:']
assignees: ['freshgiammi']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please, make sure this is not a duplicate before filing it.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: bug_description
    attributes:
      label: Bug description
      description: Something wrong has happened apparently, how about you give me a brief description of what happened (and perhaps what should have happened)?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: What are the steps to reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        If you have anything else such as logs, screenshots, scenarios or anything else that could help track this down, feel free to add it here!
