import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import GitHubButton from 'react-github-btn';
import Lightning from '~/assets/lightning.svg';

const Home: NextPage = () => {
  const [bolts, setBolts] = useState<JSX.Element[]>([]);

  useEffect(() => {
    // Doing this prevents hydration issues.
    // See: https://nextjs.org/docs/messages/react-hydration-error

    // This is a bit wack. Canvas would be far superior to SVG, but it'll be enough for now.
    setBolts(
      Array.from({ length: 30 }).map((_, i) => (
        <Lightning
          key={i}
          className='bolt'
          style={{
            top: `${Math.floor(Math.random() * 100)}vh`,
            left: `${Math.floor(Math.random() * 100)}vw`,
            animationDelay: `${Math.floor(Math.random() * 5)}s`,
            overflow: 'hidden',
          }}
        />
      ))
    );
  }, []);

  return (
    <>
      <Head>
        <title>Supercharged Next</title>
        <meta name='description' content='Generated by ⚡ Supercharged Next' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Background bolts. Isn't this fun? */}
      <div
        className='absolute overflow-hidden min-h-full min-w-full cursor-default select-none inset-0 fade-div-out'
        style={{ zIndex: '-1' }}
      >
        {bolts.map((bolt) => bolt)}
      </div>
      <section className='p-6 flex-center-column h-full'>
        <h1 className='text-5xl md:text-6xl text-center font-bold'>
          Welcome to{' '}
          <a className='text-blue-600 hover:underline' href='https://github.com/freshgiammi-lab/supercharged-next'>
            ⚡ Supercharged Next!
          </a>
        </h1>
        <div className='text-center mt-16'>
          <p className='text-2xl pb-2'>A Next.js starter kit whose 🔋 batteries are supercharged. Includes: </p>
          <ul className='pb-2'>
            <li>
              <span>⚡ Next.js</span>
            </li>
            <li>
              <span>⚛️ React v18 (with TypeScript)</span>
            </li>
            <li>
              <span>✨ Tailwind CSS 3</span>
            </li>
            <li>
              <span>🔍 ESLint</span>
            </li>
            <li>
              <span>💅 Prettier</span>
            </li>
            <li>
              <span>🐶 Husky & Lint-Staged</span>
            </li>
            <li>
              <a
                className='text-blue-600 hover:underline'
                rel='noreferrer noopener'
                target='_blank'
                href='https://github.com/freshgiammi-lab/supercharged-next#features'
              >
                ... and much more!
              </a>
            </li>
          </ul>
          <div className='flex-center-row github-btns'>
            <GitHubButton
              href='https://github.com/freshgiammi-lab/supercharged-next/generate'
              data-icon='octicon-repo-template'
              data-size='large'
              aria-label='Use this template freshgiammi-lab/supercharged-next on GitHub'
            >
              Use this template
            </GitHubButton>
            <GitHubButton
              href='https://github.com/freshgiammi-lab/supercharged-next'
              data-icon='octicon-star'
              data-size='large'
              data-show-count='true'
              aria-label='Star freshgiammi-lab/supercharged-next on GitHub'
            >
              Star
            </GitHubButton>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
