/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AiManifestoRouteImport } from './routes/ai-manifesto'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainBlogRouteRouteImport } from './routes/_main/blog/route'
import { Route as MainCraftRouteRouteImport } from './routes/_main/craft/route'
import { Route as MainThoughtsRouteRouteImport } from './routes/_main/thoughts/route'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as MainAboutIndexRouteImport } from './routes/_main/about/index'
import { Route as MainBlogIndexRouteImport } from './routes/_main/blog/index'
import { Route as MainCraftIndexRouteImport } from './routes/_main/craft/index'
import { Route as MainFindsIndexRouteImport } from './routes/_main/finds/index'
import { Route as MainThoughtsIndexRouteImport } from './routes/_main/thoughts/index'
import { Route as MainWorkIndexRouteImport } from './routes/_main/work/index'
import { Route as MainBlogSlugIndexRouteImport } from './routes/_main/blog/$slug/index'
import { Route as MainCraftConfettiIndexRouteImport } from './routes/_main/craft/confetti/index'
import { Route as MainCraftParticlesIndexRouteImport } from './routes/_main/craft/particles/index'
import { Route as MainCraftPolaroidStackIndexRouteImport } from './routes/_main/craft/polaroid-stack/index'
import { Route as MainCraftScrollableIndexRouteImport } from './routes/_main/craft/scrollable/index'
import { Route as MainCraftSkeletonIndexRouteImport } from './routes/_main/craft/skeleton/index'
import { Route as MainThoughtsSlugIndexRouteImport } from './routes/_main/thoughts/$slug/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AiManifestoRoute = AiManifestoRouteImport.update({
  id: '/ai-manifesto',
  path: '/ai-manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogRouteRoute = MainBlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MainRoute,
} as any)
const MainCraftRouteRoute = MainCraftRouteRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => MainRoute,
} as any)
const MainThoughtsRouteRoute = MainThoughtsRouteRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => MainRoute,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAboutIndexRoute = MainAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainBlogRouteRoute,
} as any)
const MainCraftIndexRoute = MainCraftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainCraftRouteRoute,
} as any)
const MainFindsIndexRoute = MainFindsIndexRouteImport.update({
  id: '/finds/',
  path: '/finds/',
  getParentRoute: () => MainRoute,
} as any)
const MainThoughtsIndexRoute = MainThoughtsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainThoughtsRouteRoute,
} as any)
const MainWorkIndexRoute = MainWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogSlugIndexRoute = MainBlogSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => MainBlogRouteRoute,
} as any)
const MainCraftConfettiIndexRoute = MainCraftConfettiIndexRouteImport.update({
  id: '/confetti/',
  path: '/confetti/',
  getParentRoute: () => MainCraftRouteRoute,
} as any)
const MainCraftParticlesIndexRoute = MainCraftParticlesIndexRouteImport.update({
  id: '/particles/',
  path: '/particles/',
  getParentRoute: () => MainCraftRouteRoute,
} as any)
const MainCraftPolaroidStackIndexRoute =
  MainCraftPolaroidStackIndexRouteImport.update({
    id: '/polaroid-stack/',
    path: '/polaroid-stack/',
    getParentRoute: () => MainCraftRouteRoute,
  } as any)
const MainCraftScrollableIndexRoute =
  MainCraftScrollableIndexRouteImport.update({
    id: '/scrollable/',
    path: '/scrollable/',
    getParentRoute: () => MainCraftRouteRoute,
  } as any)
const MainCraftSkeletonIndexRoute = MainCraftSkeletonIndexRouteImport.update({
  id: '/skeleton/',
  path: '/skeleton/',
  getParentRoute: () => MainCraftRouteRoute,
} as any)
const MainThoughtsSlugIndexRoute = MainThoughtsSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => MainThoughtsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/ai-manifesto': typeof AiManifestoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/blog': typeof MainBlogRouteRouteWithChildren
  '/craft': typeof MainCraftRouteRouteWithChildren
  '/thoughts': typeof MainThoughtsRouteRouteWithChildren
  '/og/$': typeof OgSplatRoute
  '/about/': typeof MainAboutIndexRoute
  '/blog/': typeof MainBlogIndexRoute
  '/craft/': typeof MainCraftIndexRoute
  '/finds/': typeof MainFindsIndexRoute
  '/thoughts/': typeof MainThoughtsIndexRoute
  '/work/': typeof MainWorkIndexRoute
  '/blog/$slug/': typeof MainBlogSlugIndexRoute
  '/craft/confetti/': typeof MainCraftConfettiIndexRoute
  '/craft/particles/': typeof MainCraftParticlesIndexRoute
  '/craft/polaroid-stack/': typeof MainCraftPolaroidStackIndexRoute
  '/craft/scrollable/': typeof MainCraftScrollableIndexRoute
  '/craft/skeleton/': typeof MainCraftSkeletonIndexRoute
  '/thoughts/$slug/': typeof MainThoughtsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/ai-manifesto': typeof AiManifestoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/og/$': typeof OgSplatRoute
  '/': typeof MainIndexRoute
  '/about': typeof MainAboutIndexRoute
  '/blog': typeof MainBlogIndexRoute
  '/craft': typeof MainCraftIndexRoute
  '/finds': typeof MainFindsIndexRoute
  '/thoughts': typeof MainThoughtsIndexRoute
  '/work': typeof MainWorkIndexRoute
  '/blog/$slug': typeof MainBlogSlugIndexRoute
  '/craft/confetti': typeof MainCraftConfettiIndexRoute
  '/craft/particles': typeof MainCraftParticlesIndexRoute
  '/craft/polaroid-stack': typeof MainCraftPolaroidStackIndexRoute
  '/craft/scrollable': typeof MainCraftScrollableIndexRoute
  '/craft/skeleton': typeof MainCraftSkeletonIndexRoute
  '/thoughts/$slug': typeof MainThoughtsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/ai-manifesto': typeof AiManifestoRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/_main/blog': typeof MainBlogRouteRouteWithChildren
  '/_main/craft': typeof MainCraftRouteRouteWithChildren
  '/_main/thoughts': typeof MainThoughtsRouteRouteWithChildren
  '/og/$': typeof OgSplatRoute
  '/_main/': typeof MainIndexRoute
  '/_main/about/': typeof MainAboutIndexRoute
  '/_main/blog/': typeof MainBlogIndexRoute
  '/_main/craft/': typeof MainCraftIndexRoute
  '/_main/finds/': typeof MainFindsIndexRoute
  '/_main/thoughts/': typeof MainThoughtsIndexRoute
  '/_main/work/': typeof MainWorkIndexRoute
  '/_main/blog/$slug/': typeof MainBlogSlugIndexRoute
  '/_main/craft/confetti/': typeof MainCraftConfettiIndexRoute
  '/_main/craft/particles/': typeof MainCraftParticlesIndexRoute
  '/_main/craft/polaroid-stack/': typeof MainCraftPolaroidStackIndexRoute
  '/_main/craft/scrollable/': typeof MainCraftScrollableIndexRoute
  '/_main/craft/skeleton/': typeof MainCraftSkeletonIndexRoute
  '/_main/thoughts/$slug/': typeof MainThoughtsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-manifesto'
    | '/feed.xml'
    | '/blog'
    | '/craft'
    | '/thoughts'
    | '/og/$'
    | '/about/'
    | '/blog/'
    | '/craft/'
    | '/finds/'
    | '/thoughts/'
    | '/work/'
    | '/blog/$slug/'
    | '/craft/confetti/'
    | '/craft/particles/'
    | '/craft/polaroid-stack/'
    | '/craft/scrollable/'
    | '/craft/skeleton/'
    | '/thoughts/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-manifesto'
    | '/feed.xml'
    | '/og/$'
    | '/'
    | '/about'
    | '/blog'
    | '/craft'
    | '/finds'
    | '/thoughts'
    | '/work'
    | '/blog/$slug'
    | '/craft/confetti'
    | '/craft/particles'
    | '/craft/polaroid-stack'
    | '/craft/scrollable'
    | '/craft/skeleton'
    | '/thoughts/$slug'
  id:
    | '__root__'
    | '/_main'
    | '/ai-manifesto'
    | '/feed.xml'
    | '/_main/blog'
    | '/_main/craft'
    | '/_main/thoughts'
    | '/og/$'
    | '/_main/'
    | '/_main/about/'
    | '/_main/blog/'
    | '/_main/craft/'
    | '/_main/finds/'
    | '/_main/thoughts/'
    | '/_main/work/'
    | '/_main/blog/$slug/'
    | '/_main/craft/confetti/'
    | '/_main/craft/particles/'
    | '/_main/craft/polaroid-stack/'
    | '/_main/craft/scrollable/'
    | '/_main/craft/skeleton/'
    | '/_main/thoughts/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AiManifestoRoute: typeof AiManifestoRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  OgSplatRoute: typeof OgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-manifesto': {
      id: '/ai-manifesto'
      path: '/ai-manifesto'
      fullPath: '/ai-manifesto'
      preLoaderRoute: typeof AiManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog': {
      id: '/_main/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MainBlogRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/craft': {
      id: '/_main/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof MainCraftRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/thoughts': {
      id: '/_main/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof MainThoughtsRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/about/': {
      id: '/_main/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof MainAboutIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainBlogRouteRoute
    }
    '/_main/craft/': {
      id: '/_main/craft/'
      path: '/'
      fullPath: '/craft/'
      preLoaderRoute: typeof MainCraftIndexRouteImport
      parentRoute: typeof MainCraftRouteRoute
    }
    '/_main/finds/': {
      id: '/_main/finds/'
      path: '/finds'
      fullPath: '/finds/'
      preLoaderRoute: typeof MainFindsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/thoughts/': {
      id: '/_main/thoughts/'
      path: '/'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof MainThoughtsIndexRouteImport
      parentRoute: typeof MainThoughtsRouteRoute
    }
    '/_main/work/': {
      id: '/_main/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof MainWorkIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/$slug/': {
      id: '/_main/blog/$slug/'
      path: '/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof MainBlogSlugIndexRouteImport
      parentRoute: typeof MainBlogRouteRoute
    }
    '/_main/craft/confetti/': {
      id: '/_main/craft/confetti/'
      path: '/confetti'
      fullPath: '/craft/confetti/'
      preLoaderRoute: typeof MainCraftConfettiIndexRouteImport
      parentRoute: typeof MainCraftRouteRoute
    }
    '/_main/craft/particles/': {
      id: '/_main/craft/particles/'
      path: '/particles'
      fullPath: '/craft/particles/'
      preLoaderRoute: typeof MainCraftParticlesIndexRouteImport
      parentRoute: typeof MainCraftRouteRoute
    }
    '/_main/craft/polaroid-stack/': {
      id: '/_main/craft/polaroid-stack/'
      path: '/polaroid-stack'
      fullPath: '/craft/polaroid-stack/'
      preLoaderRoute: typeof MainCraftPolaroidStackIndexRouteImport
      parentRoute: typeof MainCraftRouteRoute
    }
    '/_main/craft/scrollable/': {
      id: '/_main/craft/scrollable/'
      path: '/scrollable'
      fullPath: '/craft/scrollable/'
      preLoaderRoute: typeof MainCraftScrollableIndexRouteImport
      parentRoute: typeof MainCraftRouteRoute
    }
    '/_main/craft/skeleton/': {
      id: '/_main/craft/skeleton/'
      path: '/skeleton'
      fullPath: '/craft/skeleton/'
      preLoaderRoute: typeof MainCraftSkeletonIndexRouteImport
      parentRoute: typeof MainCraftRouteRoute
    }
    '/_main/thoughts/$slug/': {
      id: '/_main/thoughts/$slug/'
      path: '/$slug'
      fullPath: '/thoughts/$slug/'
      preLoaderRoute: typeof MainThoughtsSlugIndexRouteImport
      parentRoute: typeof MainThoughtsRouteRoute
    }
  }
}

interface MainBlogRouteRouteChildren {
  MainBlogIndexRoute: typeof MainBlogIndexRoute
  MainBlogSlugIndexRoute: typeof MainBlogSlugIndexRoute
}

const MainBlogRouteRouteChildren: MainBlogRouteRouteChildren = {
  MainBlogIndexRoute: MainBlogIndexRoute,
  MainBlogSlugIndexRoute: MainBlogSlugIndexRoute,
}

const MainBlogRouteRouteWithChildren = MainBlogRouteRoute._addFileChildren(
  MainBlogRouteRouteChildren,
)

interface MainCraftRouteRouteChildren {
  MainCraftIndexRoute: typeof MainCraftIndexRoute
  MainCraftConfettiIndexRoute: typeof MainCraftConfettiIndexRoute
  MainCraftParticlesIndexRoute: typeof MainCraftParticlesIndexRoute
  MainCraftPolaroidStackIndexRoute: typeof MainCraftPolaroidStackIndexRoute
  MainCraftScrollableIndexRoute: typeof MainCraftScrollableIndexRoute
  MainCraftSkeletonIndexRoute: typeof MainCraftSkeletonIndexRoute
}

const MainCraftRouteRouteChildren: MainCraftRouteRouteChildren = {
  MainCraftIndexRoute: MainCraftIndexRoute,
  MainCraftConfettiIndexRoute: MainCraftConfettiIndexRoute,
  MainCraftParticlesIndexRoute: MainCraftParticlesIndexRoute,
  MainCraftPolaroidStackIndexRoute: MainCraftPolaroidStackIndexRoute,
  MainCraftScrollableIndexRoute: MainCraftScrollableIndexRoute,
  MainCraftSkeletonIndexRoute: MainCraftSkeletonIndexRoute,
}

const MainCraftRouteRouteWithChildren = MainCraftRouteRoute._addFileChildren(
  MainCraftRouteRouteChildren,
)

interface MainThoughtsRouteRouteChildren {
  MainThoughtsIndexRoute: typeof MainThoughtsIndexRoute
  MainThoughtsSlugIndexRoute: typeof MainThoughtsSlugIndexRoute
}

const MainThoughtsRouteRouteChildren: MainThoughtsRouteRouteChildren = {
  MainThoughtsIndexRoute: MainThoughtsIndexRoute,
  MainThoughtsSlugIndexRoute: MainThoughtsSlugIndexRoute,
}

const MainThoughtsRouteRouteWithChildren =
  MainThoughtsRouteRoute._addFileChildren(MainThoughtsRouteRouteChildren)

interface MainRouteChildren {
  MainBlogRouteRoute: typeof MainBlogRouteRouteWithChildren
  MainCraftRouteRoute: typeof MainCraftRouteRouteWithChildren
  MainThoughtsRouteRoute: typeof MainThoughtsRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainAboutIndexRoute: typeof MainAboutIndexRoute
  MainFindsIndexRoute: typeof MainFindsIndexRoute
  MainWorkIndexRoute: typeof MainWorkIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainBlogRouteRoute: MainBlogRouteRouteWithChildren,
  MainCraftRouteRoute: MainCraftRouteRouteWithChildren,
  MainThoughtsRouteRoute: MainThoughtsRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainAboutIndexRoute: MainAboutIndexRoute,
  MainFindsIndexRoute: MainFindsIndexRoute,
  MainWorkIndexRoute: MainWorkIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AiManifestoRoute: AiManifestoRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  OgSplatRoute: OgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
