/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as MainAboutIndexRouteImport } from './routes/_main/about/index'
import { Route as MainBlogIndexRouteImport } from './routes/_main/blog/index'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainShowcaseIndexRouteImport } from './routes/_main/showcase/index'
import { Route as MainThoughtsIndexRouteImport } from './routes/_main/thoughts/index'
import { Route as MainWorkIndexRouteImport } from './routes/_main/work/index'
import { Route as ApiReadsSlugRouteImport } from './routes/api/reads.$slug'
import { Route as MainBlogSlugIndexRouteImport } from './routes/_main/blog/$slug/index'
import { Route as MainShowcasePolaroidStackIndexRouteImport } from './routes/_main/showcase/polaroid-stack/index'
import { Route as MainThoughtsIdIndexRouteImport } from './routes/_main/thoughts/$id/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAboutIndexRoute = MainAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRoute,
} as any)
const MainShowcaseIndexRoute = MainShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => MainRoute,
} as any)
const MainThoughtsIndexRoute = MainThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => MainRoute,
} as any)
const MainWorkIndexRoute = MainWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => MainRoute,
} as any)
const ApiReadsSlugRoute = ApiReadsSlugRouteImport.update({
  id: '/api/reads/$slug',
  path: '/api/reads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MainBlogSlugIndexRoute = MainBlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => MainRoute,
} as any)
const MainShowcasePolaroidStackIndexRoute =
  MainShowcasePolaroidStackIndexRouteImport.update({
    id: '/showcase/polaroid-stack/',
    path: '/showcase/polaroid-stack/',
    getParentRoute: () => MainRoute,
  } as any)
const MainThoughtsIdIndexRoute = MainThoughtsIdIndexRouteImport.update({
  id: '/thoughts/$id/',
  path: '/thoughts/$id/',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/reads/$slug': typeof ApiReadsSlugRoute
  '/about/': typeof MainAboutIndexRoute
  '/blog/': typeof MainBlogIndexRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/showcase/': typeof MainShowcaseIndexRoute
  '/thoughts/': typeof MainThoughtsIndexRoute
  '/work/': typeof MainWorkIndexRoute
  '/blog/$slug/': typeof MainBlogSlugIndexRoute
  '/showcase/polaroid-stack/': typeof MainShowcasePolaroidStackIndexRoute
  '/thoughts/$id/': typeof MainThoughtsIdIndexRoute
}
export interface FileRoutesByTo {
  '/api/activity': typeof ApiActivityRoute
  '/': typeof MainIndexRoute
  '/api/reads/$slug': typeof ApiReadsSlugRoute
  '/about': typeof MainAboutIndexRoute
  '/blog': typeof MainBlogIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/showcase': typeof MainShowcaseIndexRoute
  '/thoughts': typeof MainThoughtsIndexRoute
  '/work': typeof MainWorkIndexRoute
  '/blog/$slug': typeof MainBlogSlugIndexRoute
  '/showcase/polaroid-stack': typeof MainShowcasePolaroidStackIndexRoute
  '/thoughts/$id': typeof MainThoughtsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/api/activity': typeof ApiActivityRoute
  '/_main/': typeof MainIndexRoute
  '/api/reads/$slug': typeof ApiReadsSlugRoute
  '/_main/about/': typeof MainAboutIndexRoute
  '/_main/blog/': typeof MainBlogIndexRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/showcase/': typeof MainShowcaseIndexRoute
  '/_main/thoughts/': typeof MainThoughtsIndexRoute
  '/_main/work/': typeof MainWorkIndexRoute
  '/_main/blog/$slug/': typeof MainBlogSlugIndexRoute
  '/_main/showcase/polaroid-stack/': typeof MainShowcasePolaroidStackIndexRoute
  '/_main/thoughts/$id/': typeof MainThoughtsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/activity'
    | '/api/reads/$slug'
    | '/about/'
    | '/blog/'
    | '/projects/'
    | '/showcase/'
    | '/thoughts/'
    | '/work/'
    | '/blog/$slug/'
    | '/showcase/polaroid-stack/'
    | '/thoughts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/activity'
    | '/'
    | '/api/reads/$slug'
    | '/about'
    | '/blog'
    | '/projects'
    | '/showcase'
    | '/thoughts'
    | '/work'
    | '/blog/$slug'
    | '/showcase/polaroid-stack'
    | '/thoughts/$id'
  id:
    | '__root__'
    | '/_main'
    | '/api/activity'
    | '/_main/'
    | '/api/reads/$slug'
    | '/_main/about/'
    | '/_main/blog/'
    | '/_main/projects/'
    | '/_main/showcase/'
    | '/_main/thoughts/'
    | '/_main/work/'
    | '/_main/blog/$slug/'
    | '/_main/showcase/polaroid-stack/'
    | '/_main/thoughts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ApiActivityRoute: typeof ApiActivityRoute
  ApiReadsSlugRoute: typeof ApiReadsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/about/': {
      id: '/_main/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof MainAboutIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/showcase/': {
      id: '/_main/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof MainShowcaseIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/thoughts/': {
      id: '/_main/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof MainThoughtsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/work/': {
      id: '/_main/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof MainWorkIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/reads/$slug': {
      id: '/api/reads/$slug'
      path: '/api/reads/$slug'
      fullPath: '/api/reads/$slug'
      preLoaderRoute: typeof ApiReadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/blog/$slug/': {
      id: '/_main/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof MainBlogSlugIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/showcase/polaroid-stack/': {
      id: '/_main/showcase/polaroid-stack/'
      path: '/showcase/polaroid-stack'
      fullPath: '/showcase/polaroid-stack/'
      preLoaderRoute: typeof MainShowcasePolaroidStackIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/thoughts/$id/': {
      id: '/_main/thoughts/$id/'
      path: '/thoughts/$id'
      fullPath: '/thoughts/$id/'
      preLoaderRoute: typeof MainThoughtsIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAboutIndexRoute: typeof MainAboutIndexRoute
  MainBlogIndexRoute: typeof MainBlogIndexRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
  MainShowcaseIndexRoute: typeof MainShowcaseIndexRoute
  MainThoughtsIndexRoute: typeof MainThoughtsIndexRoute
  MainWorkIndexRoute: typeof MainWorkIndexRoute
  MainBlogSlugIndexRoute: typeof MainBlogSlugIndexRoute
  MainShowcasePolaroidStackIndexRoute: typeof MainShowcasePolaroidStackIndexRoute
  MainThoughtsIdIndexRoute: typeof MainThoughtsIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAboutIndexRoute: MainAboutIndexRoute,
  MainBlogIndexRoute: MainBlogIndexRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
  MainShowcaseIndexRoute: MainShowcaseIndexRoute,
  MainThoughtsIndexRoute: MainThoughtsIndexRoute,
  MainWorkIndexRoute: MainWorkIndexRoute,
  MainBlogSlugIndexRoute: MainBlogSlugIndexRoute,
  MainShowcasePolaroidStackIndexRoute: MainShowcasePolaroidStackIndexRoute,
  MainThoughtsIdIndexRoute: MainThoughtsIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ApiActivityRoute: ApiActivityRoute,
  ApiReadsSlugRoute: ApiReadsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
