// Auto-generated by vite-static-assets-plugin. Do not edit.
declare module 'virtual:static-assets' {
  export type StaticAssetPath =
    "favicon.svg" |
    "fonts/departuremono/DepartureMono-Regular.woff2" |
    "images/404.jpg" |
    "images/about/photo-01.jpg" |
    "images/about/photo-02.jpg" |
    "images/about/photo-03.jpg" |
    "images/about/photo-04.jpg" |
    "images/about/photo-05.jpg" |
    "images/about/photo-06.jpg" |
    "images/about/photo-08.jpg" |
    "images/about/photo-10.jpg" |
    "images/about/photo-12.jpg" |
    "images/avatar.jpg" |
    "images/me.jpg";

  /**
   * Represents the known directories containing static assets.
   * '.' represents the root directory.
   */
  export type StaticAssetDirectory =
    "." |
    "fonts/" |
    "fonts/departuremono/" |
    "images/" |
    "images/about/";

  /**
   * Represents the relative paths of files located *directly* within a specific directory.
   * Use '.' for the root directory.
   * @template Dir - A directory path string literal type from StaticAssetDirectory.
   */
  export type FilesInFolder<Dir extends '.' | StaticAssetDirectory> =
    Dir extends '.'
      ? Exclude<StaticAssetPath, `${string}/${string}`>
      : Extract<StaticAssetPath, `${Dir}${string}`> extends infer Match
        ? Match extends `${Dir}${infer FileName}`
          ? FileName extends `${string}/${string}`
            ? never
            : Match
          : never
        : never;

  /**
   * Gets the URL for a specific static asset
   * @param path Path to the asset
   * @returns The URL for the asset
   */
  export function staticAssets(path: StaticAssetPath): string;
}
