/**
 * Storybook stand-in for `virtual:static-assets` (aliased in vite.config.ts).
 *
 * The real module is generated by the app's staticAssetsPlugin, which also regenerates its
 * `src/static-assets.d.ts` on every run and misplaces it when run from Storybook's config dir.
 * In dev, asset urls are publicDir-relative either way, so the identity function is exact.
 */
export function staticAssets<T extends string>(path: T): T {
  return path
}
